/* DO NOT EDIT THIS FILE - it is machine generated */
#include "decodeRadarData.h"
#include <QString>
#include <iostream>
#include <jni.h>
/* Header for class MJni */

#ifndef _Included_MJni
#    define _Included_MJni
#    ifdef __cplusplus
extern "C"
{
#    endif
    /*
     * Class:     MJni
     * Method:    add
     * Signature: (II)I
     */
    JNIEXPORT void JNICALL Java_org_jeecg_modules_camera_jni_decodeRadarDataJni_inference(JNIEnv*, jobject, jstring jstr);
#    ifdef __cplusplus
}
#    endif
#endif
