//////////////////////////////不按规定车道行驶///////////////////////////////////////////////////////////////////
/* DO NOT EDIT THIS FILE - it is machine generated */
#include "truckoccupylane.h"
#include <jni.h>
/* Header for class MJni */

#ifndef _Included_MJni
#    define _Included_MJni
#    ifdef __cplusplus
extern "C"
{
#    endif
    /*
     * Class:     MJni
     * Method:    add
     * Signature: (II)I
     */
    JNIEXPORT jstring JNICALL Java_org_jeecg_modules_camera_jni_MJni_inference(JNIEnv*, jobject, jstring);
    JNIEXPORT void JNICALL    Java_org_jeecg_modules_camera_jni_MJni_creator(JNIEnv*, jobject);
    JNIEXPORT void JNICALL    Java_org_jeecg_modules_camera_jni_MJni_delete(JNIEnv*, jobject);
    //    TruckCVLibrary::Functions myfunctions;
    Truckoccupylane* truckdetector = nullptr;
    // std::shared_ptr<Truckoccupylane> truckdetector = nullptr;
#    ifdef __cplusplus
}
#    endif
#endif
