////////////////////////////不按规定保持车距行驶///////////////////////////////////////////////////////////////////
///* DO NOT EDIT THIS FILE - it is machine generated */
#include "carnokeepdistance.h"
#include <jni.h>
/* Header for class MJni */

#ifndef _Included_MJni
#    define _Included_MJni
#    ifdef __cplusplus
extern "C"
{
#    endif
    /*
     * Class:     MJni
     * Method:    add
     * Signature: (II)I
     */
    JNIEXPORT jstring JNICALL Java_org_jeecg_modules_camera_jni_carnokeepdistance_inference(JNIEnv*, jobject, jstring);
    JNIEXPORT void JNICALL    Java_org_jeecg_modules_camera_jni_carnokeepdistance_creator(JNIEnv*, jobject);
    JNIEXPORT void JNICALL    Java_org_jeecg_modules_camera_jni_carnokeepdistance_delete(JNIEnv*, jobject);
    //    TruckCVLibrary::Functions myfunctions;
    CarNoKeepDistance* carDetector = nullptr;
    // std::shared_ptr<CarNoKeepDistance> carDetector = nullptr;

#    ifdef __cplusplus
}
#    endif
#endif
